### ISSUE TITLE
clang: error: cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by codelgj** [nothinglo/NISwGSP#10]
[Hi,](url) i am trying to modify and run your xcode project. Xcode shows "clang: error: cannot specify -o when generating multiple output files", which setting shall I look for to fix this issue? Thanks  
the snapshot of the error info: "https://www.dropbox.com/s/5idcfnafiyw5j3z/Screenshot%202017-08-04%2013.09.10.png?dl=0"

**Comment by codelgj** [comment]
this issue is solved!

**Comment by jiaoy12** [comment]
I meet the same problem with you and the website open error 404, Could you tell me the solution of you ?

**Comment by junedgar** [comment]
@jiaoy12 Did you solve this problem?

**Comment by junedgar** [comment]
@LGuojie-nus  can you show me some details to solve this problem?

**Comment by mpelang** [comment]
@jiaoy12 @junedgar 
actually it's not solved on XCode :(  , I just used visual studio instead... you may also try with VS

**Comment by junedgar** [comment]
I solved this proble by Set "Enable Index-While-Building Functionality" to "No".  I found the same problem in [here](https://forums.developer.apple.com/thread/87722) . But i encountered another problem!
